### PR TITLE
support peerDependencies >= react 16

### PR DESCRIPTION
**Pull request by nishila2**
I have upgraded react version to 18.2.0 as @storybook/addons need to react 18.2.0. Please verify all my changes.

### CODE REVIEW

**Comment by nishila2** [comment]
@vilvaathibanpb Please have a look at my PR.

**Comment by vilvaathibanpb** [comment]
@nishila2 I doubt if that's all the changes. I will test it by Monday and let you know.

**Comment by nishila2** [comment]
@vilvaathibanpb , @coderkevin  any update ?

**Comment by vilvaathibanpb** [comment]
Hello @nishila2 ,
Sorry, it took some time for me to update you on this. Because this PR is incomplete and wouldn't work. I have made the necessary changes and tested it. Now, this plugin is compatible with React 18. Let me know if you face anymore issues. 

Closing the PR and the issue.

**Comment by vilvaathibanpb** [comment]
Fixed here - https://github.com/product-ride/storybook-addon-vscode-source/commit/4aad1ad844494a41f8da8548e8c7d6453052980b

**Pull request closed without merging**
